
name: Gradle Package

on:
  push:
     branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
   
    
    steps:


    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.9.0'


    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew
  
    - name: Build with Gradle
     # run: ./gradlew build -Ptgtok=${{ secrets.MY_BOT }} -Pmongo_uri=${{ secrets.MY_DB }}
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
       arguments: build -Ptgtok=${{ secrets.MY_BOT }} -Pmongo_uri=${{ secrets.MY_DB }}

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v13
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        use_existing_version_if_available: false
        application_name: victorina-bot
        environment_name: Victorina-bot-env
        version_label: ${{ github.sha }}
        region: eu-central-1
        deployment_package: bot/build/libs/bot.jar



    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # the publishing section of your build.gradle
#    - name: Publish to GitHub Packages
#      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
#      with:
#        arguments: publish
#      env:
#        USERNAME: ${{ github.actor }}
#        TOKEN: ${{ secrets.GITHUB_TOKEN }}



